import { domainToASCII } from "node:url";

type Level = "healthy" | "warning" | "error";
type Finding = { label: string; value: string; status?: "ok" | "warn" | "bad" };
type Answer = { name: string; type: number; TTL: number; data: string };
type DnsPacket = { Status: number; Answer?: Answer[]; Authority?: Answer[]; AD?: boolean };
type ProviderResult = { provider: string; ms: number; data: DnsPacket };
type Region = { code:string; location:string; continent:string; lat:number; lon:number; subnet:string };
const buckets = new Map<string, { count: number; reset: number }>();
const regions:Region[]=[
  {code:"SFO",location:"San Francisco, US",continent:"North America",lat:37.77,lon:-122.42,subnet:"8.8.8.0/24"},
  {code:"YYZ",location:"Toronto, Canada",continent:"North America",lat:43.65,lon:-79.38,subnet:"24.48.0.0/16"},
  {code:"GRU",location:"São Paulo, Brazil",continent:"South America",lat:-23.55,lon:-46.63,subnet:"200.160.0.0/16"},
  {code:"LHR",location:"London, UK",continent:"Europe",lat:51.51,lon:-0.13,subnet:"81.2.69.0/24"},
  {code:"FRA",location:"Frankfurt, Germany",continent:"Europe",lat:50.11,lon:8.68,subnet:"80.156.0.0/16"},
  {code:"JNB",location:"Johannesburg, South Africa",continent:"Africa",lat:-26.20,lon:28.05,subnet:"196.25.0.0/16"},
  {code:"DXB",location:"Dubai, UAE",continent:"Asia",lat:25.20,lon:55.27,subnet:"5.32.0.0/16"},
  {code:"BOM",location:"Mumbai, India",continent:"Asia",lat:19.08,lon:72.88,subnet:"49.44.0.0/16"},
  {code:"SIN",location:"Singapore",continent:"Asia",lat:1.35,lon:103.82,subnet:"103.6.0.0/16"},
  {code:"NRT",location:"Tokyo, Japan",continent:"Asia",lat:35.68,lon:139.69,subnet:"133.0.0.0/16"},
  {code:"SYD",location:"Sydney, Australia",continent:"Oceania",lat:-33.87,lon:151.21,subnet:"1.40.0.0/16"},
  {code:"AKL",location:"Auckland, New Zealand",continent:"Oceania",lat:-36.85,lon:174.76,subnet:"202.27.0.0/16"}
];

function result(tool:string,target:string,started:number,provider:string,summary:string,status:Level,findings:Finding[],records?:Array<Record<string,string|number>>,note?:string){
  return Response.json({tool,target,provider,summary,status,findings,records,note,checkedAt:new Date().toISOString(),durationMs:Date.now()-started},{headers:{"cache-control":"no-store","x-content-type-options":"nosniff"}});
}
function domain(input:string){const raw=input.trim().replace(/^https?:\/\//i,"").split(/[/?#]/)[0].replace(/\.$/,"");const value=domainToASCII(raw).toLowerCase();if(!value||value.length>253||! /^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/.test(value))throw new Error("Enter a valid public domain or hostname.");return value;}
function values(packet:DnsPacket){return (packet.Answer||[]).map(answer=>answer.data.replace(/^"|"$/g,""));}
function privateIp(input:string){const ip=input.toLowerCase().replace(/^\[|\]$/g,"");if(ip.includes(":"))return ip==="::1"||ip==="::"||/^(fc|fd|fe8|fe9|fea|feb|2001:db8)/.test(ip);const p=ip.split(".").map(Number);if(p.length!==4||p.some(n=>!Number.isInteger(n)||n<0||n>255))return true;const[a,b]=p;return a===0||a===10||a===127||a>=224||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||(a===100&&b>=64&&b<=127);}
function reverseIp(ip:string){if(!ip.includes(":"))return ip.split(".").reverse().join(".")+".in-addr.arpa";const parts=ip.split("::"),left=parts[0]?parts[0].split(":"):[],right=parts[1]?parts[1].split(":"):[];return[...left,...Array(8-left.length-right.length).fill("0"),...right].map(v=>v.padStart(4,"0")).join("").split("").reverse().join(".")+".ip6.arpa";}

async function query(name:string,type:string,provider:"google"|"cloudflare"="google"):Promise<ProviderResult>{
  const defs={google:["Google Public DNS","https://dns.google/resolve"],cloudflare:["Cloudflare 1.1.1.1","https://cloudflare-dns.com/dns-query"]} as const;
  const [label,base]=defs[provider],started=Date.now();const response=await fetch(`${base}?name=${encodeURIComponent(name)}&type=${encodeURIComponent(type)}${provider==="google"?"&edns_client_subnet=0.0.0.0/0":""}`,{headers:{accept:"application/dns-json","user-agent":"CipherScope-DNS/1.0"},signal:AbortSignal.timeout(4500)});if(!response.ok)throw new Error(`${label} returned ${response.status}`);const data=await response.json() as DnsPacket;if(typeof data.Status!=="number")throw new Error(`${label} returned an invalid DNS response`);return{provider:label,ms:Date.now()-started,data};
}
async function regionalQuery(name:string,type:string,region:Region){const started=Date.now(),response=await fetch(`https://dns.google/resolve?name=${encodeURIComponent(name)}&type=${encodeURIComponent(type)}&edns_client_subnet=${encodeURIComponent(region.subnet)}`,{headers:{accept:"application/dns-json","user-agent":"CipherScope-DNS/1.0"},signal:AbortSignal.timeout(4500)});if(!response.ok)throw new Error(`Regional DNS returned ${response.status}`);const data=await response.json() as DnsPacket;if(typeof data.Status!=="number")throw new Error("Regional DNS returned an invalid response");return{region,ms:Date.now()-started,data};}
async function publicHost(host:string){if(host==="localhost"||host.endsWith(".local")||host.endsWith(".internal"))throw new Error("Private and local destinations are blocked.");if(/^[\da-f:.]+$/i.test(host)){if(privateIp(host))throw new Error("Private, reserved, and metadata destinations are blocked.");return;}const checked=await Promise.allSettled([query(host,"A"),query(host,"AAAA")]);const ips=checked.flatMap(item=>item.status==="fulfilled"?values(item.value.data):[]);if(!ips.length)throw new Error("The hostname did not resolve publicly.");if(ips.some(privateIp))throw new Error("The hostname resolves to a private or reserved address.");}

async function dnsCheck(targetInput:string,type:string,expected:string,expectedMode:string,started:number){
  if(!["contains","exact","regex"].includes(expectedMode))expectedMode="contains";if(expected.length>120)throw new Error("Expected values are limited to 120 characters.");let matcher:(value:string)=>boolean;if(!expected)matcher=()=>true;else if(expectedMode==="exact")matcher=value=>value.toLowerCase()===expected.toLowerCase();else if(expectedMode==="regex"){let expression:RegExp;try{expression=new RegExp(expected,"i");}catch{throw new Error("Enter a valid regular expression.");}matcher=value=>expression.test(value);}else matcher=value=>value.toLowerCase().includes(expected.toLowerCase());
  const target=type==="PTR"&&/^[\da-f:.]+$/i.test(targetInput)?reverseIp(targetInput):domain(targetInput);const[providerSettled,regionSettled]=await Promise.all([Promise.allSettled([query(target,type,"google"),query(target,type,"cloudflare")]),Promise.allSettled(regions.map(region=>regionalQuery(target,type,region)))]);const good=providerSettled.flatMap(item=>item.status==="fulfilled"?[item.value]:[]),regional=regionSettled.flatMap(item=>item.status==="fulfilled"?[item.value]:[]);if(!good.length&&!regional.length)throw new Error("DNS providers could not be reached. Please retry in a moment.");const evidence=good.length?good:regional.map(item=>({provider:item.region.location,ms:item.ms,data:item.data})),answering=evidence.filter(item=>item.data.Status===0&&values(item.data).length>0),sets=answering.map(item=>values(item.data).map(v=>v.toLowerCase()).sort().join("|")),agree=sets.length<2||new Set(sets).size===1,match=!expected||answering.every(item=>values(item.data).some(matcher)),regionalMatched=regional.filter(item=>!expected||values(item.data).some(matcher)).length,hasAnswer=answering.length>0,hasDnsError=evidence.every(item=>item.data.Status!==0);const healthy=hasAnswer&&agree&&match;const regionalRows=regional.map(item=>{const answers=values(item.data),matched=!expected||answers.some(matcher),ttls=(item.data.Answer||[]).map(a=>a.TTL);return{code:item.region.code,location:item.region.location,continent:item.region.continent,status:answers.length?(matched?"resolved":"different"):item.data.Status===3?"not found":"no answer",answer:answers.join(" · ")||"—",ttl:ttls.length?Math.min(...ttls):"—",time_ms:item.ms,lat:item.region.lat,lon:item.region.lon,source:"Google ECS"};});const providerRows=good.map(item=>{const ttls=(item.data.Answer||[]).map(a=>a.TTL);return{code:"DOH",location:item.provider,continent:"Anycast provider",status:item.data.Status===0?(values(item.data).length?"resolved":"no answer"):item.data.Status===3?"not found":`rcode ${item.data.Status}`,answer:values(item.data).join(" · ")||"—",ttl:ttls.length?Math.min(...ttls):"—",time_ms:item.ms,source:"Independent DoH"};});const summary=hasDnsError?"The domain was not found":hasAnswer?(agree?"DNS resolved successfully":"DNS resolved with regional differences"):"No records of this type were returned";return result("dns",targetInput,started,`12 regional views + ${good.length} DoH provider${good.length===1?"":"s"}`,summary,healthy?"healthy":"warning",[
    {label:"Resolution",value:hasAnswer?"Answer received":hasDnsError?"Domain not found":"No records returned",status:hasAnswer?"ok":"warn"},{label:"Regional coverage",value:`${regional.length} of ${regions.length} views`,status:regional.length>=8?"ok":"warn"},{label:"Expected value",value:expected?`${regionalMatched} of ${regional.length} regions matched`:"Not configured",status:match?"ok":"warn"},{label:"Provider agreement",value:agree?"Consistent":"Answers differ",status:agree?"ok":"warn"},{label:"DNSSEC validation",value:evidence.some(item=>item.data.AD)?"Observed":"Not asserted",status:evidence.some(item=>item.data.AD)?"ok":"warn"}
  ],[...regionalRows,...providerRows],"World points are regionalized answers produced with EDNS Client Subnet hints through Google Public DNS, plus independent anycast DoH comparisons. They indicate regional answer variation but are not physical probes located in each city.");
}
async function domainCheck(input:string,started:number){const target=domain(input),types=["NS","SOA","DS","DNSKEY","CAA","MX","TXT"],all=await Promise.all(types.map(async type=>({type,q:await query(target,type)}))),get=(type:string)=>values(all.find(item=>item.type===type)!.q.data),txt=get("TXT");const findings:Finding[]=[{label:"Authoritative nameservers",value:get("NS").length?`${get("NS").length} published`:"Missing",status:get("NS").length>=2?"ok":"bad"},{label:"Start of authority",value:get("SOA").length?"Present":"Missing",status:get("SOA").length?"ok":"bad"},{label:"DNSSEC chain",value:get("DS").length&&get("DNSKEY").length?"Delegation signed":"Unsigned or incomplete",status:get("DS").length&&get("DNSKEY").length?"ok":"warn"},{label:"CAA policy",value:get("CAA").length?`${get("CAA").length} record(s)`:"Unrestricted",status:get("CAA").length?"ok":"warn"},{label:"Mail routing",value:get("MX").length?`${get("MX").length} exchanger(s)`:"No MX",status:get("MX").length?"ok":"warn"},{label:"SPF policy",value:txt.some(v=>v.toLowerCase().includes("v=spf1"))?"Present":"Not found",status:txt.some(v=>v.toLowerCase().includes("v=spf1"))?"ok":"warn"}];const warnings=findings.filter(f=>f.status!=="ok").length;return result("domain",target,started,"Google Public DNS",warnings>2?"Domain configuration has gaps":"Domain fundamentals look sound",warnings?"warning":"healthy",findings,all.flatMap(item=>(item.q.data.Answer||[]).map(a=>({record:item.type,ttl:a.TTL,value:a.data}))));}
async function emailCheck(input:string,selector:string,started:number){const target=domain(input),sel=(selector||"default").replace(/[^a-z0-9_-]/gi,"").slice(0,63),defs=[{label:"MX",name:target,type:"MX"},{label:"SPF",name:target,type:"TXT"},{label:"DMARC",name:`_dmarc.${target}`,type:"TXT"},{label:"DKIM",name:`${sel}._domainkey.${target}`,type:"TXT"},{label:"MTA-STS",name:`_mta-sts.${target}`,type:"TXT"},{label:"TLS-RPT",name:`_smtp._tls.${target}`,type:"TXT"}],all=await Promise.all(defs.map(async d=>({...d,q:await query(d.name,d.type)}))),get=(label:string)=>values(all.find(item=>item.label===label)!.q.data),has=(label:string,needle:string)=>get(label).some(v=>v.toLowerCase().includes(needle));const findings:Finding[]=[{label:"Mail exchangers",value:get("MX").length?`${get("MX").length} published`:"Missing",status:get("MX").length?"ok":"bad"},{label:"SPF",value:has("SPF","v=spf1")?"Policy present":"Not found",status:has("SPF","v=spf1")?"ok":"warn"},{label:"DMARC",value:has("DMARC","v=dmarc1")?(get("DMARC").join(" ").includes("p=reject")?"Reject policy":"Policy present"):"Not found",status:has("DMARC","v=dmarc1")?"ok":"warn"},{label:`DKIM · ${sel}`,value:has("DKIM","p=")?"Key published":"Not found",status:has("DKIM","p=")?"ok":"warn"},{label:"MTA-STS",value:has("MTA-STS","v=stsv1")?"Signal present":"Not configured",status:has("MTA-STS","v=stsv1")?"ok":"warn"},{label:"TLS reporting",value:has("TLS-RPT","v=tlsrptv1")?"Configured":"Not configured",status:has("TLS-RPT","v=tlsrptv1")?"ok":"warn"}];const warnings=findings.filter(f=>f.status!=="ok").length;return result("email",target,started,"Google Public DNS",warnings?`${warnings} mail policy improvement(s) found`:"Mail authentication signals are present",warnings?"warning":"healthy",findings,all.flatMap(item=>(item.q.data.Answer||[]).map(a=>({record:item.label,name:item.name,ttl:a.TTL,value:a.data}))),"DNS presence checks do not prove delivery. Configure a mail diagnostics provider for full SPF recursion and cryptographic DKIM validation.");}
async function ipCheck(input:string,started:number){const target=input.trim().replace(/^\[|\]$/g,"");if(privateIp(target))throw new Error("Enter a valid public IPv4 or IPv6 address.");const[rdap,ptr]=await Promise.all([fetch(`https://rdap.org/ip/${encodeURIComponent(target)}`,{headers:{accept:"application/rdap+json"},signal:AbortSignal.timeout(8000)}),query(reverseIp(target),"PTR")]);if(!rdap.ok)throw new Error(`RDAP returned ${rdap.status}`);const d=await rdap.json() as Record<string,unknown>,ptrs=values(ptr.data),name=String(d.name||d.handle||"Unspecified network"),country=String(d.country||"Not published");return result("ip",target,started,"RDAP bootstrap + DNS",ptrs.length?"Registration and reverse DNS resolved":"Registration resolved; reverse DNS is absent",ptrs.length?"healthy":"warning",[{label:"Address family",value:target.includes(":")?"IPv6":"IPv4",status:"ok"},{label:"Classification",value:"Public routable",status:"ok"},{label:"Registered network",value:name,status:"ok"},{label:"Country code",value:country,status:country==="Not published"?"warn":"ok"},{label:"Reverse DNS",value:ptrs.join(" · ")||"Not configured",status:ptrs.length?"ok":"warn"},{label:"Range",value:`${String(d.startAddress||"—")} – ${String(d.endAddress||"—")}`,status:"ok"}],[{source:"RDAP",handle:String(d.handle||"—"),name,country,start_address:String(d.startAddress||"—"),end_address:String(d.endAddress||"—")},{source:"PTR",handle:ptrs.join(" · ")||"—",name:"Reverse DNS",country:"—",start_address:"—",end_address:"—"}]);}
async function safeUrl(input:string){let raw=input.trim();if(!/^https?:\/\//i.test(raw))raw=`https://${raw}`;const url=new URL(raw);if(!["http:","https:"].includes(url.protocol)||url.username||url.password)throw new Error("Enter a public HTTP or HTTPS URL without credentials.");await publicHost(url.hostname);return url;}
async function httpCheck(input:string,started:number){let url=await safeUrl(input);const records:Array<Record<string,string|number>>=[];let final:Response|undefined;for(let hop=0;hop<6;hop++){const r=await fetch(url,{redirect:"manual",headers:{"user-agent":"CipherScope/1.0",accept:"text/html,*/*;q=0.7"},signal:AbortSignal.timeout(9000)});records.push({hop:hop+1,status:r.status,url:url.toString(),location:r.headers.get("location")||"—"});if(r.status<300||r.status>=400||!r.headers.get("location")){final=r;break;}url=new URL(r.headers.get("location")!,url);await publicHost(url.hostname);}if(!final)throw new Error("Redirect chain exceeded five hops.");const h=final.headers,findings:Finding[]=[{label:"Final status",value:String(final.status),status:final.ok?"ok":"warn"},{label:"HTTPS",value:url.protocol==="https:"?"Encrypted":"Plain HTTP",status:url.protocol==="https:"?"ok":"bad"},{label:"HSTS",value:h.has("strict-transport-security")?"Present":"Missing",status:h.has("strict-transport-security")?"ok":"warn"},{label:"Content policy",value:h.has("content-security-policy")?"Present":"Missing",status:h.has("content-security-policy")?"ok":"warn"},{label:"Frame protection",value:h.has("x-frame-options")||h.get("content-security-policy")?.includes("frame-ancestors")?"Present":"Missing",status:h.has("x-frame-options")||h.get("content-security-policy")?.includes("frame-ancestors")?"ok":"warn"},{label:"Compression",value:h.get("content-encoding")||"Not advertised",status:h.has("content-encoding")?"ok":"warn"}];const warnings=findings.filter(f=>f.status!=="ok").length;return result("http",url.toString(),started,"Direct public fetch",warnings?"Response received with security opportunities":"Response and baseline security headers look sound",warnings?"warning":"healthy",findings,records,"Every redirect destination is revalidated; private, reserved, link-local, and metadata networks are blocked.");}
async function tlsCheck(input:string,started:number){const target=domain(input);await publicHost(target);const[site,ct]=await Promise.allSettled([fetch(`https://${target}/`,{method:"HEAD",redirect:"manual",signal:AbortSignal.timeout(9000)}),fetch(`https://crt.sh/?q=${encodeURIComponent(target)}&output=json`,{headers:{accept:"application/json"},signal:AbortSignal.timeout(9000)})]);const endpoint=site.status==="fulfilled"?site.value:null;let certs:Array<Record<string,unknown>>=[];if(ct.status==="fulfilled"&&ct.value.ok){try{certs=(await ct.value.json() as Array<Record<string,unknown>>).slice(0,20);}catch{}}const latest=certs.sort((a,b)=>String(b.not_after||"").localeCompare(String(a.not_after||"")))[0],expires=latest?.not_after?new Date(String(latest.not_after)):null,days=expires?Math.ceil((expires.getTime()-Date.now())/86400000):null;const findings:Finding[]=[{label:"HTTPS reachability",value:endpoint?`HTTP ${endpoint.status}`:"Connection failed",status:endpoint?"ok":"bad"},{label:"HSTS",value:endpoint?.headers.has("strict-transport-security")?"Present":"Not observed",status:endpoint?.headers.has("strict-transport-security")?"ok":"warn"},{label:"CT certificates",value:certs.length?`${certs.length} recent entries`:"None returned",status:certs.length?"ok":"warn"},{label:"Latest CT expiry",value:expires?expires.toLocaleDateString("en-US",{year:"numeric",month:"short",day:"numeric"}):"Unavailable",status:days===null?"warn":days<14?"bad":days<30?"warn":"ok"},{label:"Issuer",value:String(latest?.issuer_name||"Unavailable").slice(0,90),status:latest?"ok":"warn"},{label:"Hostname evidence",value:String(latest?.name_value||"Unavailable").split("\n").slice(0,2).join(" · "),status:latest?"ok":"warn"}];const bad=findings.some(f=>f.status==="bad");return result("tls",target,started,"Direct HTTPS + certificate transparency",bad?"TLS evidence needs attention":"TLS endpoint and public certificate evidence found",bad?"error":"warning",findings,certs.slice(0,10).map(c=>({common_name:String(c.common_name||"—"),issuer:String(c.issuer_name||"—").slice(0,70),not_before:String(c.not_before||"—"),not_after:String(c.not_after||"—")})),"Certificate Transparency is supporting evidence, not a live handshake chain. Configure a TLS provider for cipher and chain validation.");}

export async function POST(request:Request,{params}:{params:Promise<{type:string}>}){const started=Date.now();try{const ip=request.headers.get("cf-connecting-ip")||"anonymous",now=Date.now(),bucket=buckets.get(ip);if(!bucket||bucket.reset<now)buckets.set(ip,{count:1,reset:now+60000});else if(++bucket.count>30)return Response.json({error:"Rate limit reached. Try again in one minute."},{status:429});const{type}=await params,payload=await request.json() as {target?:string;recordType?:string;selector?:string;expected?:string;expectedMode?:string},target=payload.target?.trim()||"";if(!target||target.length>500)return Response.json({error:"A valid target is required."},{status:400});if(type==="dns")return dnsCheck(target,(payload.recordType||"A").toUpperCase(),payload.expected||"",payload.expectedMode||"contains",started);if(type==="domain")return domainCheck(target,started);if(type==="email")return emailCheck(target,payload.selector||"default",started);if(type==="ip")return ipCheck(target,started);if(type==="http")return httpCheck(target,started);if(type==="tls")return tlsCheck(target,started);return Response.json({error:"Unknown diagnostic tool."},{status:404});}catch(error){return Response.json({error:error instanceof Error?error.message:"The check could not be completed."},{status:400,headers:{"cache-control":"no-store"}});}}
