import { and, desc, eq, lt } from "drizzle-orm";
import { getDb } from "@/db";
import { incidents, monitorRuns, monitors } from "@/db/schema";

function toHex(buffer:ArrayBuffer){return [...new Uint8Array(buffer)].map(value=>value.toString(16).padStart(2,"0")).join("");}
async function signature(value:string,secret:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return toHex(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(value)));}
function equal(a:string,b:string){if(a.length!==b.length)return false;let out=0;for(let i=0;i<a.length;i++)out|=a.charCodeAt(i)^b.charCodeAt(i);return out===0;}

export async function POST(request:Request){ const secret=process.env.SCHEDULER_HMAC_SECRET||""; const timestamp=request.headers.get("x-cipherscope-timestamp")||""; const supplied=request.headers.get("x-cipherscope-signature")||""; const raw=await request.text(); if(!secret||!timestamp||Math.abs(Date.now()-Number(timestamp))>300000||!equal(await signature(`${timestamp}.${raw}`,secret),supplied))return Response.json({error:"Invalid scheduler signature"},{status:401}); const payload:{batchId?:string}=raw?JSON.parse(raw):{}; const batchId=payload.batchId||timestamp; const db=getDb(); const due=await db.select().from(monitors).where(and(eq(monitors.status,"active"),lt(monitors.nextRunAt,new Date().toISOString()))).limit(25); const completed=[] as Array<{id:string;outcome:string}>;
  for(const monitor of due){ const idempotencyKey=`${batchId}:${monitor.id}`; const existing=await db.select({id:monitorRuns.id}).from(monitorRuns).where(eq(monitorRuns.idempotencyKey,idempotencyKey)).limit(1); if(existing.length)continue; const started=Date.now(); let outcome:"healthy"|"warning"|"error"="error"; let result:Record<string,unknown>={error:"check failed"}; try{ const check=await fetch(new URL(`/api/checks/${monitor.tool}`,request.url),{method:"POST",headers:{"content-type":"application/json","x-cipherscope-internal":"monitor"},body:JSON.stringify({target:monitor.target,...JSON.parse(monitor.configJson)})}); result=await check.json() as Record<string,unknown>; outcome=(result.status as typeof outcome)||"error"; }catch(error){result={error:error instanceof Error?error.message:"check failed"};}
    await db.insert(monitorRuns).values({id:crypto.randomUUID(),monitorId:monitor.id,idempotencyKey,outcome,resultJson:JSON.stringify(result),durationMs:Date.now()-started}); const previous=await db.select().from(monitorRuns).where(eq(monitorRuns.monitorId,monitor.id)).orderBy(desc(monitorRuns.checkedAt)).limit(2); const prior=previous[1]?.outcome; if(outcome!=="healthy"&&(!prior||prior==="healthy")){await db.insert(incidents).values({id:crypto.randomUUID(),monitorId:monitor.id,summary:String(result.summary||`${monitor.tool} check changed to ${outcome}`)});} if(outcome==="healthy"&&prior&&prior!=="healthy"){await db.update(incidents).set({state:"resolved",resolvedAt:new Date().toISOString()}).where(and(eq(incidents.monitorId,monitor.id),eq(incidents.state,"open")));}
    const next=new Date(Date.now()+monitor.intervalMinutes*60000).toISOString(); await db.update(monitors).set({lastRunAt:new Date().toISOString(),nextRunAt:next}).where(eq(monitors.id,monitor.id)); completed.push({id:monitor.id,outcome}); }
  const cutoff=new Date(Date.now()-30*86400000).toISOString(); await db.delete(monitorRuns).where(lt(monitorRuns.checkedAt,cutoff)); return Response.json({batchId,processed:completed.length,results:completed}); }
